### GET request to example server
POST http://localhost:4004/api/doctors
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Saurav",
  "lastName": "Kumar",
  "specialization": "Dermo",
  "email": "saurav@g.com",
  "phoneNumber": "129-456-7880",
  "licenseNumber": "MD13301",
  "experienceYears": 3,
  "clinicAddress": "Patna, Bihar",
  "status": "ACTIVE",
  "consultationFee": 1400
}

###