### GET request to example server
POST http://localhost:4004/api/doctors
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Aditya",
  "lastName": "Kumar",
  "specialization": "Cardiology",
  "email": "aditya@g.com",
  "phoneNumber": "127-456-7880",
  "licenseNumber": "MD13341",
  "experienceYears": 11,
  "clinicAddress": "Patna, Bihar",
  "status": "ACTIVE",
  "consultationFee": 14000.50
}

###