### GET request to example server
GET http://localhost:4004/api/doctors/slots/available?doctorId=f6349d10-683a-4653-acca-53b24b9a50e6&date=2025-11-06

#GET http://localhost:8081/doctors/slots/available?specialization=Cardiology&date=2025-07-11


###