### Post request to example server
POST http://localhost:4004/api/appointments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "patientId": "be31a193-8171-43d1-bbe4-798e70829e49",
  "doctorId": "1851c36c-c85d-445d-8497-a97619f7e9e9",
  "appointmentDateTime": "2025-07-18T11:30",
  "status": "Booked by admin",
  "doctorSlotId": "521ddd61-f818-4c91-9474-28dcbeca1d29"
}
###