### Post request to example server
POST http://localhost:4004/api/appointments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "patientId": "dd09764b-ff73-459b-99e2-efcbcc8f852d",
  "doctorId": "832bb548-0986-4fb1-b0dc-1376dddaa94d",
  "appointmentDateTime": "2025-12-27T10:30",
  "status": "Booked by admin",
  "doctorSlotId": "f5f03be4-6905-4bb9-91a8-28e62fe0ed24"
}
###