### PUT request to example server
PUT http://localhost:4004/api/appointments/d8480676-5922-49f4-8be0-9bad42b64662/reschedule
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "doctorId": "0cfc2951-1d3c-4778-8c2f-5b09d9a45d3c",
  "appointmentDateTime": "2025-07-22T01:00",
  "reason": "Reschedule due to conflict",
  "doctorSlotId": "10d03abe-11d4-45fd-88f0-91f62a5d5e87"
}

###