### PUT request to example server
PUT http://localhost:4004/api/appointments/25fdcc6a-1e00-4f50-9a18-e1002c880e93/reschedule
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "doctorId": "f6349d10-683a-4653-acca-53b24b9a50e6",
  "appointmentDateTime": "2025-11-06T11:00",
  "reason": "Reschedule due to conflict",
  "doctorSlotId": "d9d85066-1364-42cb-aaa4-bcc59f9d950f"
}

###