### PUT request to example server
PUT http://localhost:4004/api/appointments/011c6d78-3393-495c-a650-182d56f244fd/reschedule
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "doctorId": "e1a2b3c4-d5e6-7f89-a0b1-c2d3e4f56789",
  "appointmentDateTime": "2028-12-30T10:00",
  "reason": "Reschedule due to conflict"
}

###