### GET request to example server
POST http://localhost:4004/auth/register
Content-Type: application/json

{
  "email": "david.wilson@example.com",
  "password": "password123",
  "role": "PATIENT"
}
###