### GET request to example server
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Patient A",
  "email": "patient_a@example.com",
  "address": "123 Main St",
  "dateOfBirth": "1990-01-01",
  "contact": "1234567890",
  "gender": "Female",
  "emergencyContact": "0987654321"
}

###