### GET request to example server
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sunil",
  "email": "sunil04393@gmail.com",
  "address": "Raipur",
  "dateOfBirth": "1998-02-01",
  "contact": "1143211312",
  "gender": "Male",
  "emergencyContact": "9997954321"
}

###