### GET request to example server
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Roushan Jaiswal",
  "email": "rous04393@gmail.com",
  "address": "Patna, Bihar",
  "dateOfBirth": "1990-01-01",
  "contact": "1143211329",
  "gender": "Male",
  "emergencyContact": "9987954321"
}

###