### GET request to example server
GET http://localhost:4001/billing/bills/87e303d8-7125-401a-8266-bd70d8791015
Authorization: Bearer {{token}}

###

# you can use this endpoint after completing the appointment then see id in bill db.