### GET request to example server
POST http://localhost:4001/billing/bills/8250b03f-faeb-48dc-bd54-bd41590b62d5/pay
Content-Type: application/json

{
  "paymentMethod": "UPI"
}
###

//here we need to add bill-id from bill table.