### GET request to example server
POST http://localhost:4001/billing/bills/6049bc51-a4df-418a-bd21-676d1b4b45cd/pay
Content-Type: application/json

{
  "paymentMethod": "UPI"
}
###

//here we need to add bill-id from bill table.